### ISSUE TITLE
Which is the tensorflow and kears version?

### ISSUE THREAD

**Issue by zk19991208** [mit-ll/tornet#1]
Hello, I read your article and am very interested in your work. Can you share your keras and tensorflow versions? I would like to try running your test code.

**Comment by markveilletteLL** [comment]
Thanks for the question.    We used version `2.13` of tensorflow, and version `2.13.1` of keras to train the model.   However, the code and pretrained model should work in newer versions as well.  

I will update the requirements file to reflect this.

**Comment by LiAlH4** [comment]
I have to comment that actually only tensorflow==2.13.1 will work for the jupyter notebook. At least the script `notebooks/ModelTraining_Tensorflow.ipynb` will face a compiling error for the command `model.fit(...)` on my local machine.

**Comment by markveilletteLL** [comment]
Thanks for letting us know -- can you please post the error?   We can work on making it backwards compatible

**Comment by comlor** [comment]
I am running into errors as well during training.  I am running the command in the readme.md in the repo.  
<code> python scripts/tornado_detection/train_tornado_tf.py scripts/tornado_detection/config/params.json </code>

I am able to successfully run the Model_Train_Tensorflow notebook without issue on the same below configuration

Python environment details:
UPDATE: I scrapped by python venv and rebuilt the environment.  I noticed prevously that tensorflow was not utilizing my GPU.  I pulled the latest versions of tensorflow and keras and updated below details.  
<code>
```
(venv) user@laptop:~/Documents/Projects/tornet$ pip3 show tensorflow
Name: tensorflow
Version: 2.16.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
```

```
(venv) user@laptop:~/Documents/Projects/tornet$ pip3 show keras
Name: keras
Version: 3.3.3
Summary: Deep learning for humans.
Home-page: https://keras.io/
```

```
(venv) user@laptop:~/Documents/Projects/tornet$ python3 --version
Python 3.10.12
```
</code>

This is the error i receive running the Train CNN Baseline Model:
<code>
```
2024-05-12 13:30:12.591535: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
Traceback (most recent call last):
  File "~/Documents/Projects/tornet/scripts/tornado_detection/train_tornado_tf.py", line 225, in <module>
    main(config)
  File "~/Documents/Projects/tornet/scripts/tornado_detection/train_tornado_tf.py", line 135, in main
    nn = build_model(shape=in_shapes,
  File "~/venv/tornet/lib/python3.10/site-packages/tornet/models/tf/cnn_baseline.py", line 59, in build_model
    x,c = vgg_block(x,c, filters=start_filters,   ksize=3, l2_reg=l2_reg, n_convs=2, drop_rate=0.1)   # (60,120)
  File "~/venv/tornet/lib/python3.10/site-packages/tornet/models/tf/cnn_baseline.py", line 95, in vgg_block
    x,c = CoordConv2D(filters=filters,
  File "~/venv/tornet/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3107, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
```
</code>

As an aside.  During the initial setup and install.  After installing the requirements and running <code>pip3 install .</code>.  The entire module did not install into my site package.  I had to go through the directory structure and add <code> "\_\_init\_\_.py" </code> file in a bunch of locations for the module to fully install correctly.

**Comment by markveilletteLL** [comment]
@comlor    Apologies, in a recent push I forgot to commit a file.  the `too many positional arguments` error should now be fixed in https://github.com/mit-ll/tornet/commit/c5fa03c557f297b65a58ed050f44a4d63b654f0d
